---
- hosts: all
  become: true
  tasks:
  - name: Create entries in /etc/hosts for all nodes
    lineinfile:
      path: /etc/hosts
      line: "{{ hostvars[item]['ansible_host'] }} {{ hostvars[item]['ansible_hostname'] }} {{ item }}"
      regexp: "^.* {{ item }}$"
      create: no
      state: present
    with_items:
      - "{{ ansible_play_hosts }}"
  - name: Update all packages
    yum:
      name: "*"
      state: latest

- hosts: etcd_master[0]
  roles:
    - role: andrewrothstein.pki
      pki_dir: /home/centos/pki-dir
      pki_self_sign: True
      pki_ca:
        cname: ca.dac.hpc.cam.ac.uk
      pki_servers:
        - cname: dac-etcd.dac.hpc.cam.ac.uk
          include_localhost: True
          sans:
            - dac-etcd.dac.hpc.cam.ac.uk
          altips:
            - "{{ hostvars[groups['etcd_master'][0]].ansible_host }}"
        - cname: dac1.dac.hpc.cam.ac.uk
          include_localhost: True
          sans:
            - dac1.dac.hpc.cam.ac.uk
        - cname: dac2.dac.hpc.cam.ac.uk
          include_localhost: True
          sans:
            - dac2.dac.hpc.cam.ac.uk
        - cname: dac3.dac.hpc.cam.ac.uk
          include_localhost: True
          sans:
            - dac3.dac.hpc.cam.ac.uk
        - cname: dac-slurm-master.dac.hpc.cam.ac.uk
          include_localhost: True
          sans:
            - dac-slurm-master.dac.hpc.cam.ac.uk
        - cname: slurm-cpu1.dac.hpc.cam.ac.uk
          include_localhost: True
          sans:
            - slurm-cpu1.dac.hpc.cam.ac.uk
        - cname: slurm-cpu2.dac.hpc.cam.ac.uk
          include_localhost: True
          sans:
            - slurm-cpu2.dac.hpc.cam.ac.uk

- hosts: etcd_master[0]
  tasks:
    - fetch:
        src: /home/centos/pki-dir/{{item}}
        dest: "{{ inventory_dir }}/pki-dir/"
        flat: yes
      with_items:
        - ca.pem
        - ca-key.pem
        - dac-etcd.dac.hpc.cam.ac.uk.pem
        - dac-etcd.dac.hpc.cam.ac.uk-key.pem
        - dac1.dac.hpc.cam.ac.uk.pem
        - dac1.dac.hpc.cam.ac.uk-key.pem
        - dac2.dac.hpc.cam.ac.uk.pem
        - dac2.dac.hpc.cam.ac.uk-key.pem
        - dac3.dac.hpc.cam.ac.uk.pem
        - dac3.dac.hpc.cam.ac.uk-key.pem
        - dac-slurm-master.dac.hpc.cam.ac.uk.pem
        - dac-slurm-master.dac.hpc.cam.ac.uk-key.pem
        - slurm-cpu1.dac.hpc.cam.ac.uk.pem
        - slurm-cpu1.dac.hpc.cam.ac.uk-key.pem
        - slurm-cpu2.dac.hpc.cam.ac.uk.pem
        - slurm-cpu2.dac.hpc.cam.ac.uk-key.pem

- hosts: etcd
  roles:
    - role: andrewrothstein.etcd-cluster
      etcd_master_group_name: etcd_master
      etcd_pki_dir: "{{ inventory_dir }}/pki-dir"

- hosts: dac_workers:slurm_workers
  become: true
  roles:
    - geerlingguy.repo-epel
    - geerlingguy.pip

- hosts: dac_workers
  become: True
  tasks:
    - name: ensure kernel dev tools available for beegfs client autobuild
      package:
        name: kernel-devel
    - name: ensure dev tools available for beegfs client autobuild
      package:
        name: gcc
    - selinux:
        state: disabled

# TODO: should this be part of fs-ansible really?
- hosts: dac_workers:slurm_workers
  become: True
  vars:
      lustre_release: "2.12.2"
  tasks:
    - name: enable lustre server repo
      yum_repository:
        name: lustre-server
        description: lustre-server
        file: lustre-repo
        baseurl: https://downloads.whamcloud.com/public/lustre/lustre-{{ lustre_release }}/el7/patchless-ldiskfs-server
        gpgcheck: no
    - name: enable lustre client repo
      yum_repository:
        name: lustre-client
        description: lustre-client
        file: lustre-repo
        baseurl: https://downloads.whamcloud.com/public/lustre/lustre-{{ lustre_release }}/el7/client
        gpgcheck: no
    - name: enable lustre e2fs repo
      yum_repository:
        name: e2fsprogs-wc
        description: e2fsprogs-wc
        file: lustre-repo
        baseurl: https://downloads.whamcloud.com/public/e2fsprogs/latest/el7
        gpgcheck: no

- hosts: dac_workers:slurm_workers
  become: True
  vars:
      lustre_release: "2.12.2"
  tasks:
    - name: Install Lustre Server
      yum:
        name: "lustre-{{ lustre_release }}"
        state: present
    - name: Install LVM
      yum:
        name: "lvm2"
        state: present

- hosts: dac_workers:slurm_workers
  become: True
  vars:
      lustre_release: "2.12.2"
  tasks:
    - name: Install Lustre Client
      yum:
        name: "lustre-client-dkms-{{ lustre_release }}"
        state: present

- hosts: dac_workers
  roles:
    - role: data-acc

- hosts: dac_workers[0]
  become: true
  become_user: dac
  tasks:
    - name: Create ssh key for dac user for fs-ansible
      shell: |
        ssh-keygen -f /var/lib/dac/.ssh/id_rsa -t rsa -N ''
        cat /var/lib/dac/.ssh/id_rsa.pub >> /var/lib/dac/.ssh/authorized_keys
      args:
         creates: /var/lib/dac/.ssh/id_rsa
    - name: Pull Keys
      synchronize:
        mode: pull
        src:  /var/lib/dac/.ssh/
        dest: "{{ inventory_dir }}/.dac.ssh/"
        recursive: yes
        delete: yes

- hosts: dac_workers:slurm_workers
  become: true
  tasks:
    - name: create data_acc group
      become: yes
      become_user: root
      group:
        name: dac
        state: present
    - name: create data_acc group
      become: yes
      become_user: root
      group:
        name: etcd
        state: present
    - name: create data_acc user
      become: yes
      become_user: root
      user:
        name: dac
        group: dac
        groups: etcd,wheel # Get access to etcd private key, and sudo for ansible
        home: /var/lib/dac
        state: present
    - name: Push Keys for dac user for fs-ansible
      synchronize:
        mode: push
        src: "{{ inventory_dir }}/.dac.ssh/"
        dest:  /var/lib/dac/.ssh/
        recursive: yes
    - name: trust host keys
      shell: |
        ssh-keyscan {{ hostvars[item]['ansible_host'] }} >> /var/lib/dac/.ssh/known_hosts
        ssh-keyscan {{ hostvars[item]['ansible_hostname'] }} >> /var/lib/dac/.ssh/known_hosts
        ssh-keyscan {{ item }} >> /var/lib/dac/.ssh/known_hosts
        touch /var/lib/dac/.ssh/.known{{ hostvars[item]['ansible_host'] }}
      args:
         creates: "/var/lib/dac/.ssh/.known{{ hostvars[item]['ansible_host'] }}"
      with_items: "{{ ansible_play_hosts }}"
    - name: Fix up permissions on .ssh
      file:
        path: /var/lib/dac/.ssh
        owner: dac
        group: dac
        recurse: yes

- hosts: dac_workers
  become: true
  tasks:
    - name: Ensure passwordless sudo for dac user
      lineinfile:
        path: /etc/sudoers.d/80-dac
        line: "dac ALL=(ALL) NOPASSWD:ALL"
        regexp: "^dac.*$"
        create: yes
        state: present

- hosts: slurm_workers
  become: true
  tasks:
    - name: Ensure passwordless sudo for dac user
      lineinfile:
        path: /etc/sudoers.d/80-dac
        line: "dac ALL=(ALL) NOPASSWD: /usr/bin/mkdir -p /dac/*, /usr/bin/chmod 770 /dac/*, /usr/bin/chmod 0600 /dac/*, /usr/bin/chown * /dac/*, /usr/bin/mount -t lustre * /dac/*, /usr/bin/umount /dac/*, /usr/sbin/losetup /dev/loop* /dac/*, /usr/sbin/losetup -d /dev/loop*, /usr/sbin/mkswap /dev/loop*, /usr/sbin/swapon /dev/loop*, /usr/sbin/swapoff /dev/loop*, /usr/bin/ln -s /dac/* /dac/*, /usr/bin/dd if=/dev/zero of=/dac/*, /usr/bin/rm -rf /dac/*, /bin/grep /dac/* /etc/mtab"
        regexp: "^dac.*$"
        create: yes
        state: present

- hosts: slurm
  become: true
  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose
    docker_users:
      - "centos"
    docker_compose_version: "1.22.0"
  roles:
    - geerlingguy.repo-epel
    - geerlingguy.pip
    - geerlingguy.docker

- hosts: slurm_master[0]
  become: true
  vars:
      recreate: false
  tasks:
    - file:
        path: /var/lib/slurm-docker/slurm-master
        state: directory
        mode: 0755
    - name: docker service description to host
      template:
        src: slurm-master.yml.j2
        dest: /var/lib/slurm-docker/slurm-master/docker-compose.yml
    - file:
        path: /etc/data-acc/pki
        state: directory
        mode: 0700
        owner: 995
        group: 995
    - name: copy etcd keys
      become: yes
      become_user: root
      copy:
        src: '{{item}}'
        dest: /etc/data-acc/pki
        owner: '995' # TODO...
        group: '995'
        mode: 0700
      with_items:
        - '{{ inventory_dir }}/pki-dir/{{inventory_hostname}}.pem'
        - '{{ inventory_dir }}/pki-dir/{{inventory_hostname}}-key.pem'
        - '{{ inventory_dir }}/pki-dir/ca.pem'
    - name: pull docker images
      # https://github.com/ansible/ansible/issues/47978
      command: docker-compose pull
      args:
        chdir: '/var/lib/slurm-docker/slurm-master'
      changed_when: False
    - docker_service:
        project_src: /var/lib/slurm-docker/slurm-master
        state: absent
        remove_volumes: yes
      when: recreate|bool
    - docker_service:
        project_src: /var/lib/slurm-docker/slurm-master
      register: output
    - name: ensure slurm cluster registered in db
      shell: |
        sleep 10 && docker exec slurmctld bash -c "/usr/bin/sacctmgr --immediate add cluster name=linux" && docker restart slurmdbd slurmctld
      register: shell_result
      changed_when: "shell_result.rc == 0"
      failed_when: "shell_result.rc != 0 and ('already exists' not in shell_result.stdout)"
      when: output.changed

- hosts: slurm_workers
  become: true
  vars:
      recreate: false
  tasks:
    - file:
        path: /var/lib/slurm-docker/slurm-worker
        state: directory
        mode: 0755
    - name: docker service description to host
      template:
        src: slurm-worker.yml.j2
        dest: /var/lib/slurm-docker/slurm-worker/docker-compose.yml
    - file:
        path: /etc/data-acc/pki
        state: directory
        mode: 0700
        owner: root
        group: root
    - name: copy etcd keys
      become: yes
      become_user: root
      copy:
        src: '{{item}}'
        dest: /etc/data-acc/pki
        owner: 'root' # TODO...
        group: 'root'
        mode: 0700
      with_items:
        - '{{ inventory_dir }}/pki-dir/{{inventory_hostname}}.pem'
        - '{{ inventory_dir }}/pki-dir/{{inventory_hostname}}-key.pem'
        - '{{ inventory_dir }}/pki-dir/ca.pem'
    - name: pull docker images
      # https://github.com/ansible/ansible/issues/47978
      command: docker-compose pull
      args:
        chdir: '/var/lib/slurm-docker/slurm-worker'
      changed_when: False
    - docker_service:
        project_src: /var/lib/slurm-docker/slurm-worker
        state: absent
        remove_volumes: yes
      when: recreate|bool
    - docker_service:
        project_src: /var/lib/slurm-docker/slurm-worker
