version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: ~/data-acc
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}

      - run: make tar
      - run: make test
      - run: bash <(curl -s https://codecov.io/bash)

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - store_artifacts:
          path: ~/data-acc/bin
