---
- name: Ensure MGS has been formatted
  command: /usr/sbin/mkfs.lustre --mgs /dev/{{ mgs }}
  register: command_result
  failed_when: "command_result.rc != 0 and ('was previously formatted for lustre' not in command_result.stderr) and command_result.rc != 17"
  changed_when: "command_result.rc == 0"
  when:
    - mgs is defined

- name: Partition disks
  block:
    - name: Add MDT Partition
      parted:
        device: "/dev/{{ item }}"
        number: 1
        part_start: "0%"
        part_end: "{{ mdt_size_mb }}MB"
        label: gpt
        state: present
      loop: "{{ (mdts.keys() + osts.keys()) | unique }}"
    - name: Add OST Partition
      parted:
        device: "/dev/{{ item }}"
        number: 2
        part_start: "{{ mdt_size_mb }}MB"
        part_end: "100%"
        label: gpt
        state: present
      loop: "{{ (mdts.keys() + osts.keys()) | unique }}"

- name: Format MDTs
  block:
    - name: Add MDT Partition
      parted:
        device: "/dev/{{ item }}"
        number: 1
        part_start: "0%"
        part_end: "{{ mdt_size_mb }}MB"
        label: gpt
        state: present
      loop: "{{ mdts.keys() }}"

    - name: Wait for MDT partition to appear in /dev
      wait_for:
        path: "/dev/{{ item }}p1"
        timeout: 30
        sleep: 5
      loop: "{{ mdts.keys() }}"

    - name: Reformat MDTs
      shell: "test -b /dev/{{ item.key }}p1 && /usr/sbin/mkfs.lustre --mdt --reformat --fsname={{ fs_name }} --index={{ item.value }} --mgsnode={{ mgsnode }}{{ lnet_suffix }} /dev/{{ item.key }}p1"
      loop: "{{ mdts|dict2items }}"

- name: Format OSTs
  block:
    - name: Add OST Partition
      parted:
         device: "/dev/{{ item }}"
         number: 2
         part_start: "{{ mdt_size_mb }}MB"
         part_end: "100%"
         label: gpt
         state: present
      loop: "{{ osts.keys() }}"

    - name: Wait for OST partition to appear in /dev
      wait_for:
        path: "/dev/{{ item }}p2"
        timeout: 30
        sleep: 5
      loop: "{{ osts.keys() }}"

    - name: Reformat OSTs
      shell: "test -b /dev/{{ item.key }}p2 && /usr/sbin/mkfs.lustre --ost --reformat --fsname={{ fs_name }} --index={{ item.value }} --mgsnode={{ mgsnode }}{{ lnet_suffix }} /dev/{{ item.key }}p2"
      loop: "{{ osts|dict2items }}"
