---
- set_fact:
    mdts: "{{ mdts | default({}) }}"
    osts: "{{ osts | default({}) }}"
    mdt_size: "{{ mdt_size | default('10%') }}"

- name: Ensure MGS has been formatted
  command: /usr/sbin/mkfs.lustre --mgs /dev/{{ mgs }}
  register: command_result
  failed_when: "command_result.rc != 0 and ('was previously formatted for lustre' not in command_result.stderr) and command_result.rc != 17"
  changed_when: "command_result.rc == 0"
  when:
    - mgs is defined

- name: Format MDTs
  block:
    - name: Remove old MDT Partition
      parted:
         device: "/dev/{{ item }}"
         number: 1
         state: absent
      loop: "{{ mdts.keys() }}"

    - name: Add MDT Partition
      parted:
        device: "/dev/{{ item }}"
        number: 1
        part_start: "0%"
        part_end: "{{ mdt_size }}"
        label: gpt
        state: present
      loop: "{{ mdts.keys() }}"

    - name: Reformat MDTs
      command: "/usr/sbin/mkfs.lustre --mdt --reformat --fsname={{ fs_name }} --index={{ item.value }} --mgsnode={{ mgsnode }}{{ lnet_suffix }} /dev/{{ item.key }}p1"
      loop: "{{ mdts|dict2items }}"
  when:
    - mdts is defined

- name: Format OST
  block:
    - name: Remove old OST Partition
      parted:
         device: "/dev/{{ item }}"
         number: 2
         state: absent
      loop: "{{ osts.keys() }}"

    - name: Add OST Partition
      parted:
         device: "/dev/{{ item }}"
         number: 2
         part_start: "{{ mdt_size }}"
         part_end: "100%"
         label: gpt
         state: present
      loop: "{{ osts.keys() }}"

    - name: Reformat OSTs
      command: "/usr/sbin/mkfs.lustre --ost --reformat --fsname={{ fs_name }} --index={{ item.value }} --mgsnode={{ mgsnode }}{{ lnet_suffix }} /dev/{{ item.key }}p2"
      loop: "{{ osts|dict2items }}"
  when:
    - osts is defined
