---
- block:
    - name: download data_acc
      get_url:
        url: '{{data_acc_tgz_url}}'
        dest: /tmp/{{data_acc_tgz}}
        checksum: '{{data_acc_checksum}}'
        timeout: '{{data_acc_download_timeout_seconds}}'
        mode: 0644
    - name: create install dir
      file:
        state: directory
        path: '{{data_acc_install_dir}}/{{data_acc_name}}'
    - name: unachive data_acc
      unarchive:
        remote_src: yes
        src: /tmp/{{data_acc_tgz}}
        dest: '{{data_acc_install_dir}}/{{data_acc_name}}'

- name: link data_acc
  file:
    src: '{{data_acc_install_dir}}/{{data_acc_name}}/bin/{{item}}'
    dest: '{{data_acc_install_dir}}/{{item}}'
    state: link
  with_items:
    - dacd
    - dacctl

- name: Install python-virtualenv
  package:
    name: python-virtualenv
    state: present

- name: Add ansible venv
  pip:
    name: ansible
    virtualenv:  "{{data_acc_install_dir}}/{{data_acc_name}}/fs-ansible/.venv"

- include_tasks: systemd.yml
  when: data_acc_install_dacd
