---
- block:
    - name: download data_acc
      become: yes
      become_user: root
#      copy:
#        src: ~/{{data_acc_tgz}}
#        dest: /tmp/{{data_acc_tgz}}
      get_url:
        url: '{{data_acc_tgz_url}}'
        dest: /tmp/{{data_acc_tgz}}
        checksum: '{{data_acc_checksum}}'
        timeout: '{{data_acc_download_timeout_seconds}}'
        mode: 0644
    - name: create install dir
      become: yes
      become_user: root
      file:
        state: directory
        path: '{{data_acc_install_dir}}/{{data_acc_name}}'
    - name: unachive data_acc
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: /tmp/{{data_acc_tgz}}
        dest: '{{data_acc_install_dir}}/{{data_acc_name}}'
  always:
    - name: delete archive
      become: yes
      become_user: root
      file:
        path: /tmp/{{data_acc_tgz}}
        state: absent

- name: link data_acc
  become: yes
  become_user: root
  file:
    src: '{{data_acc_install_dir}}/{{data_acc_name}}/bin/{{item}}'
    dest: '{{data_acc_install_dir}}/{{item}}'
    state: link
  with_items:
    - dacd
    - dacctl

- name: Install python-virtualenv
  become: yes
  become_user: root
  package:
    name: python-virtualenv
    state: present

- name: Add ansible venv
  become: yes
  become_user: root
  shell: |
      cd {{data_acc_install_dir}}/{{data_acc_name}}/fs-ansible
      virtualenv .venv
      source .venv/bin/activate
      pip install -U pip
      pip install -U 'ansible<2.8'
  args:
    creates: "{{data_acc_install_dir}}/{{data_acc_name}}/fs-ansible/.venv"

- include_tasks: systemd.yml
  when: data_acc_install_dacd
