---
- block:
    - name: download data_acc
      get_url:
        url: '{{data_acc_tgz_url}}'
        dest: /tmp/{{data_acc_tgz}}
        checksum: '{{data_acc_checksum}}'
        timeout: '{{data_acc_download_timeout_seconds}}'
        mode: 0644
    - name: create install dir
      file:
        state: directory
        path: '{{data_acc_install_dir}}/{{data_acc_name}}'
    - name: unachive data_acc
      unarchive:
        remote_src: yes
        src: /tmp/{{data_acc_tgz}}
        dest: '{{data_acc_install_dir}}/{{data_acc_name}}'

- name: link data_acc
  file:
    src: '{{data_acc_install_dir}}/{{data_acc_name}}/bin/{{item}}'
    dest: '{{data_acc_install_dir}}/{{item}}'
    state: link
  with_items:
    - dacd
    - dacctl

- name: Install python-virtualenv
  package:
    name: python-virtualenv
    state: present
  when: "'slurm' not in group_names"

- name: Add ansible venv
  pip:
    name: ansible
    virtualenv:  "{{data_acc_install_dir}}/{{data_acc_name}}/fs-ansible/.venv"
  when: "'slurm' not in group_names"

- include_tasks: systemd.yml
  when: "data_acc_install_dacd and 'slurm' not in group_names"

- name: dacd conf for slurmctld
  template:
    src: 'dacd.conf.j2'
    dest: '/etc/sysconfig/slurmctld'
    mode: 0644
  notify: Restart slurmctld
  when: "'slurm_master' in group_names"

- name: dacd conf for slurmd
  template:
    src: 'dacd.conf.j2'
    dest: '/etc/sysconfig/slurmd'
    mode: 0644
  notify: Restart slurmd
  when: "'slurm_workers' in group_names"

- name: dacctl.log
  file:
    path: /var/log/dacctl.log
    state: touch
    owner: 8900
    group: 8900
  when: "'slurm' in group_names"
