---
- name: create data_acc group
  group:
    name: '{{data_acc_group}}'
    state: present
  
- name: create data_acc user
  user:
    name: '{{data_acc_user}}'
    group: '{{data_acc_group}}'
    groups: etcd,wheel # Get access to etcd private key, and sudo for ansible
    home: '{{data_acc_data_dir}}'
    state: present

- name: create main config dir
  file:
    state: directory
    path: '{{item}}'
    owner: '{{data_acc_user}}'
    group: '{{data_acc_group}}'
    mode: 0755
  with_items:
    - /etc/data-acc
    
- name: create keys config dir
  file:
    state: directory
    path: '{{item}}'
    owner: '{{data_acc_user}}'
    group: '{{data_acc_group}}'
    mode: 0700
  with_items:
    - /etc/data-acc/pki

- name: copy keys
  copy:
    src: '{{item}}'
    dest: /etc/data-acc/pki
    remote_src: True
    owner: '{{data_acc_user}}'
    group: '{{data_acc_group}}'
    mode: 0700
  with_items:
    - '/var/lib/etcd/test-cluster-name.pki/{{inventory_hostname}}.pem'
    - '/var/lib/etcd/test-cluster-name.pki/{{inventory_hostname}}-key.pem'
    - '/var/lib/etcd/test-cluster-name.pki/ca.pem'

- name: install data_acc.service configuration
  template:
    src: 'dacd.conf.j2'
    dest: '/etc/data-acc/dacd.conf'
    owner: '{{data_acc_user}}'
    group: '{{data_acc_group}}'
    mode: 0644
        
- name: install dacd.service systemd unit
  register: data_acc_service_modified
  template:
    src: 'dacd.service.j2'
    dest: '/etc/systemd/system/dacd.service'
    mode: '0644'

- name: systemctl daemon-reload
  when: data_acc_launch and data_acc_service_modified is changed
  command: systemctl daemon-reload

- name: create fake backing files of 200MB
  command: "dd if=/dev/zero of={{item}} bs=1024 count=204800"
  args:
    creates: "{{item}}"
  with_items:
    - "{{data_acc_data_dir}}/fake_nvme0"
    - "{{data_acc_data_dir}}/fake_nvme1"
    - "{{data_acc_data_dir}}/fake_nvme2"
    - "{{data_acc_data_dir}}/fake_nvme3"
    - "{{data_acc_data_dir}}/fake_nvme4"
    - "{{data_acc_data_dir}}/fake_sdb"

- name: create loopback
  command: "losetup /dev/loop{{item.loop}} {{item.file}}"
  args:
    creates: "/dev/loop{{item.loop}}"
  with_items:
    - loop: 0
      file: "{{data_acc_data_dir}}/fake_nvme0"
    - loop: 1
      file: "{{data_acc_data_dir}}/fake_nvme1"
    - loop: 2
      file: "{{data_acc_data_dir}}/fake_nvme2"
    - loop: 3
      file: "{{data_acc_data_dir}}/fake_nvme3"
    - loop: 4
      file: "{{data_acc_data_dir}}/fake_nvme4"
    - loop: 5
      file: "{{data_acc_data_dir}}/fake_sdb"

- name: create nvme symlinks
  file:
    src: "/dev/loop{{ item.loop }}"
    dest: "/dev/nvme{{ item.loop }}n1"
    state: link
  with_items:
    - loop: 0
      file: "{{data_acc_data_dir}}/fake_nvme0"
    - loop: 1
      file: "{{data_acc_data_dir}}/fake_nvme1"
    - loop: 2
      file: "{{data_acc_data_dir}}/fake_nvme2"
    - loop: 3
      file: "{{data_acc_data_dir}}/fake_nvme3"
    - loop: 4
      file: "{{data_acc_data_dir}}/fake_nvme4"

- name: create nvme symlinks
  file:
    src: "/dev/loop5"
    dest: "/dev/sdb"
    state: link

- name: launching data_acc...
  when: data_acc_launch
  service:
    name: dacd
    enabled: yes
    state: started
