---
- name: 'Mount DAC Filesystem on clients'
  hosts: fs1-clients
  gather_facts: no
  become: no

  tasks:
    - name: Create mount point
      command: "sudo mkdir -p /dac/{{ lustre_fs_name }}"
      tags:
        - 'mount'

    - name: Check for current mount
      command: "grep {{ lustre_fs_name }} /proc/mounts"
      register: currently_mounted_result
      failed_when: currently_mounted_result.rc >= 2
      ignore_errors: yes
      tags:
        - 'mount'

    - name: Mount DAC Filesystem
      command: "sudo mount -t lustre -o nosuid,nodev,flock,lazystatfs {{ lustre_mgs_host }}@{{ lustre_lnet_network }}:/{{ lustre_fs_name }} /dac/{{ lustre_fs_name }}"
      when: currently_mounted_result.rc != 0
      async: 15
      poll: 5
      tags:
        - 'mount'

- name: 'Make benchmark directory'
  hosts: fs1-clients
  gather_facts: no
  become: no

  tasks:
    - name: Create benchmark directory
      command: "sudo mkdir -p /dac/{{ lustre_fs_name }}/mjr208"
      run_once: true
      tags:
        - 'mount'
    - name: Chown directory
      command: "sudo chown mjr208:sysadmin /dac/{{ lustre_fs_name }}/mjr208"
      run_once: true
      tags:
        - 'mount'

- name: 'Un-mount DAC Filesystem on clients'
  hosts: fs1-clients
  gather_facts: no
  become: no

  tasks:
    - name: Check for current mount
      command: "grep {{ lustre_fs_name }} /proc/mounts"
      register: currently_mounted_result
      failed_when: currently_mounted_result.rc >= 2
      tags:
        - 'unmount'

    - name: Un-Mount DAC Filesystem
      command: "sudo umount -l /dac/{{ lustre_fs_name }}"
      register: unmount_cmd
      failed_when: unmount_cmd.rc not in [0, 32]
      when: currently_mounted_result.rc == 0
      async: 30
      poll: 5
      tags:
        - 'unmount'

    - debug:
        var: unmount_cmd

    - name: Delete mount point
      command: "sudo rmdir /dac/{{ lustre_fs_name }}"
      register: rmdir_cmd
      failed_when: rmdir_cmd.rc not in [0, 1]
      tags:
        - 'unmount'

