---
- name: 'Client tunings'
  hosts: fs1-clients
  gather_facts: no
  become: no

  tasks:
    - name: Set client MDT max_rpcs_in_flight
      command: "sudo lctl set_param mdc.{{ lustre_fs_name }}*.max_rpcs_in_flight={{ lustre_max_rpcs_in_flight }}"
      tags:
        - 'client'

    - name: Set client MDT max_mod_rpcs_in_flight
      command: "sudo lctl set_param mdc.{{ lustre_fs_name }}*.max_mod_rpcs_in_flight={{ lustre_max_mod_rpcs_in_flight }}"
      tags:
        - 'client'

    - name: Set client 16M RPCs
      command: "sudo lctl set_param osc.{{ lustre_fs_name }}-OST*.max_pages_per_rpc=16M"
      tags:
        - 'client'

    - name: Set client max_read_ahead_mb
      command: "sudo lctl set_param llite.{{ lustre_fs_name }}*.max_read_ahead_mb={{ lustre_max_read_ahead_mb }}"
      tags:
        - 'client'

    - name: Set client LNET checksums
      command: "sudo lctl set_param osc.{{ lustre_fs_name }}*.checksums={{ lustre_checksums }}"
      tags:
        - 'client'

- name: 'Server tunings'
  hosts: fs1
  gather_facts: no
  become: yes

  tasks:
    - name: Enable DNE2 remote dir
      command: "lctl set_param mdt.*.enable_remote_dir=1"
      register: command_result
      failed_when: "command_result.rc != 0 and ('lctl' not in command_result.stderr)"
      tags:
        - 'server'

    - name: Enable DNE2 all users
      command: "lctl set_param mdt.*.enable_remote_dir_gid=-1"
      tags:
        - 'server'

    - name: Set server MDT max_mod_rpcs_per_client
      shell: "echo {{ lustre_mdt_max_mod_rpcs_per_client }} > /sys/module/mdt/parameters/max_mod_rpcs_per_client"
      tags:
        - 'server'

    - name: Set server OSS 16M RPCs
      shell: "lctl set_param obdfilter.*OST*.brw_size=16"
      tags:
        - 'server'

